name: deacon_school_user
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http:
  flutter_bloc:
  #flutter_svg:
  fluttertoast:
  go_router:
  shared_preferences:
  cached_network_image:
  image_picker:
  url_launcher:
  easy_localization: ^3.0.7
  #share:
  #flutter_launcher_icons: ^0.13.1
  icons_launcher: ^3.0.0
  #intl_phone_field: ^3.2.0
  #lottie: ^3.1.2
  #easy_rich_text: ^2.1.0
  flutter_dotenv: ^5.2.1
  #mobkit_dashed_border: ^0.0.6
  #timeago: ^3.7.0
  supabase_flutter: ^2.8.3
  loading_animation_widget:
  gap: ^3.0.1
  audioplayers: ^6.1.0
  just_audio: ^0.9.42
  flutter_cached_pdfview: ^0.4.3
  syncfusion_flutter_gauges: ^27.1.58
  flutter_animate: ^4.5.0
  flutter_pdfview: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

#flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/image/mainLogo.png"
#  min_sdk_android: 21

icons_launcher:
  image_path: "assets/image/ic_launcher.png"
  platforms:
    android:
      enable: true
      image_path: "assets/image/ic_launcher.png"
      notification_image: "assets/image/ic_launcher_foreground.png"
      adaptive_background_color: '#182633'
      # adaptive_background_image: "assets/image/ic_launcher_background.png"
      adaptive_foreground_image: "assets/image/ic_launcher_foreground.png"
      adaptive_round_image: "assets/image/ic_launcher.png"
      adaptive_monochrome_image: "assets/image/ic_launcher_monochrome.png"
    ios:
      enable: true
      image_path: "assets/image/ic_launcher.png"
      # For iOS 18+ (support dark and tinted)
      dark_path: "assets/image/ic_launcher.png"
      tinted_path: "assets/image/ic_launcher.png"


flutter:

  uses-material-design: true

  assets:
    #- .env
    - assets/
    - assets/image/
    #- assets/translations/
    - assets/font/
    - assets/lottie/
    #- assets/image/user/
    #- assets/image/bookTaxi/
    #- assets/image/myBooking/


  fonts:
    - family: ArefRuqaa
      fonts:
        - asset: assets/font/ArefRuqaa-Regular.ttf
        - asset: assets/font/ArefRuqaa-Bold.ttf
